### ISSUE TITLE
Implement persistent toasts

### ISSUE THREAD

**Issue by charles-dexter-ward** [mercurymedia/elm-message-toast#10]
Is there any chance to implement this feature? 

It could be usefull to use mouse click over the message to close it instead of a timeout, in some cases.

**Comment by jmpressman** [comment]
You should be able to disable the automatic disappearance (across all toasts) by not handling the message toast subscription as seen in the readme. However, if you want the toast to disappear automatically for some toasts (success messages) but not for others (error messages), I believe we would need to implement that. @mschindlerMM can you confirm?

**Comment by charles-dexter-ward** [comment]
Thanks for the answer.
Yes, the need it that.

**Comment by mschindlerMM** [comment]
> However, if you want the toast to disappear automatically for some toasts (success messages) but not for others (error messages), I believe we would need to implement that.

That is correct. I think we could implement and release that feature in the near future, as it shouldn't be too much effort.

@charles-dexter-ward Feel free to suggest your own changes and open a pull request if you'd like, which we'll be looking at soon. This could reduce the delay if it is an urgent concern for you.

**Comment by charles-dexter-ward** [comment]
I'll try. Even if I'm a beginner with Elm.
