### ISSUE TITLE
Customizable message body

### ISSUE THREAD

**Issue by frandibar** [mercurymedia/elm-message-toast#8]
Hi, first of all, nice lib!

Would you consider adding support for a more extensible message body, that supports not only a text element?
My only need is to be able to add a bold title and a body, such as:
`<b>title<b><br>text here`

Thank you.

**Comment by mschindlerMM** [comment]
@frandibar Thanks for your feedback! We are sorry for the late response and we will try to improve this. We agree that it makes sense, that a user can define a custom message body and therefore already started working on it. You can keep track of the progress on the respective PR https://github.com/mercurymedia/elm-message-toast/pull/9.

**Comment by frandibar** [comment]
@mschindlerMM this is great news! thank you :)
